[build]
  command = "npm run build"
  publish = "dist"

[dev]
  command = "vite"
  port = 3000
  targetPort = 5173

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
  force = true
[[redirects]]
  from = "/api"
  to = "/.netlify/functions/api"
  status = 200
  force = true
[[redirects]]
  from = "/api/"
  to = "/.netlify/functions/api"
  status = 200
  force = true

  